package com.didiprogrammer.youtepresta.data.repository

import com.didiprogrammer.youtepresta.data.model.FundingSource
import com.didiprogrammer.youtepresta.data.model.SourceMovement
import com.didiprogrammer.youtepresta.data.remote.SupabaseClientProvider
import io.github.jan.supabase.postgrest.postgrest
import io.github.jan.supabase.postgrest.query.Order
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.time.OffsetDateTime
import java.time.ZoneOffset

enum class MovementType(val dbValue: String) {
    INCOME("income"),
    OUTFLOW("outflow")
}

/**
 * Thrown by [FundingSourceRepository.updateMovement] and [FundingSourceRepository.deleteMovement]
 * when the target movement has a `reference_loan_id` or `reference_payment_id` — i.e. it was
 * generated by a loan or a payment, not entered manually, and must stay read-only from the
 * funding source screen.
 */
class NonManualSourceMovementException : Exception(
    "This source movement was generated by a loan or a payment and cannot be edited or deleted here."
)

/**
 * Thrown by [FundingSourceRepository.archiveSource] when the source still has at least one loan
 * in "active" or "partial" status — archiving would hide a source money is still expected to
 * move through.
 */
class SourceHasActiveLoansException : Exception(
    "This funding source has active or partially paid loans and cannot be archived yet."
)

/**
 * Thrown by [FundingSourceRepository.deleteSourceIfUnused] when the source has any loan
 * (regardless of status) or any non-manual movement referencing it — deleting it would destroy
 * traceability that must be kept. Archive it instead.
 */
class SourceInUseException : Exception(
    "This funding source has loan or payment history and cannot be deleted — archive it instead."
)

object FundingSourceRepository {

    private const val TABLE_FUNDING_SOURCES = "funding_sources"
    private const val TABLE_SOURCE_MOVEMENTS = "source_movements"
    private const val INITIAL_BALANCE_NOTE = "Saldo inicial"

    private val postgrest = SupabaseClientProvider.client.postgrest

    suspend fun getFundingSources(includeArchived: Boolean = false): List<FundingSource> =
        postgrest.from(TABLE_FUNDING_SOURCES)
            .select {
                if (!includeArchived) {
                    filter { FundingSource::isArchived eq false }
                }
                order("name", Order.ASCENDING)
            }
            .decodeList()

    suspend fun getFundingSource(sourceId: String): FundingSource =
        postgrest.from(TABLE_FUNDING_SOURCES)
            .select {
                filter { FundingSource::id eq sourceId }
            }
            .decodeSingle()

    suspend fun createFundingSource(name: String, initialBalance: Double) {
        val created = postgrest.from(TABLE_FUNDING_SOURCES)
            .insert(NewFundingSource(name = name)) {
                select()
            }
            .decodeSingle<FundingSource>()

        if (initialBalance > 0) {
            addManualMovement(
                sourceId = created.id,
                movementType = MovementType.INCOME,
                amount = initialBalance,
                notes = INITIAL_BALANCE_NOTE
            )
        }
    }

    /**
     * Combines the two questions the funding source detail screen needs answered at once (to
     * pick "Eliminar" vs "Archivar"/"Reactivar" and whether that button should be enabled)
     * without querying loans twice.
     */
    data class SourceArchiveStatus(val hasAnyLoan: Boolean, val canArchive: Boolean)

    suspend fun getArchiveStatus(sourceId: String): SourceArchiveStatus {
        val loans = LoanRepository.getLoansBySource(sourceId)
        return SourceArchiveStatus(
            hasAnyLoan = loans.isNotEmpty(),
            canArchive = loans.none { it.status == LoanStatus.ACTIVE || it.status == LoanStatus.PARTIAL }
        )
    }

    /**
     * A source can be archived as long as it has no loan still expecting activity — "active" or
     * "partial". A paid-off loan, or no loans at all, both allow archiving.
     */
    suspend fun canArchive(sourceId: String): Boolean = getArchiveStatus(sourceId).canArchive

    /**
     * Archives a source: it stops being offered for new loans/payments/manual movements, but its
     * balance and history stay exactly as they are — see [unarchiveSource] to undo. Throws
     * [SourceHasActiveLoansException] if [canArchive] would return false.
     */
    suspend fun archiveSource(sourceId: String) {
        if (!canArchive(sourceId)) {
            throw SourceHasActiveLoansException()
        }

        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::isArchived setTo true
            FundingSource::archivedAt setTo OffsetDateTime.now(ZoneOffset.UTC).toString()
        }) {
            filter { FundingSource::id eq sourceId }
        }
    }

    suspend fun unarchiveSource(sourceId: String) {
        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::isArchived setTo false
            FundingSource::archivedAt setTo null
        }) {
            filter { FundingSource::id eq sourceId }
        }
    }

    /**
     * Permanently deletes a source, but only if nothing traceable points at it: no loan ever
     * originated from it (any status, since even a paid-off loan must keep its source_id), and
     * no source_movement referencing a loan or a payment was ever recorded against it either
     * (it could have been chosen as a payment destination without ever being a loan's origin).
     * If either is true, throws [SourceInUseException] — archive the source instead. Otherwise,
     * its own manual movements are deleted first, then the source row itself.
     */
    suspend fun deleteSourceIfUnused(sourceId: String) {
        val hasLoans = LoanRepository.getLoansBySource(sourceId).isNotEmpty()
        val hasNonManualMovements = getSourceMovements(sourceId).any {
            it.referenceLoanId != null || it.referencePaymentId != null
        }
        if (hasLoans || hasNonManualMovements) {
            throw SourceInUseException()
        }

        postgrest.from(TABLE_SOURCE_MOVEMENTS).delete {
            filter { SourceMovement::sourceId eq sourceId }
        }
        postgrest.from(TABLE_FUNDING_SOURCES).delete {
            filter { FundingSource::id eq sourceId }
        }
    }

    suspend fun getSourceMovements(sourceId: String): List<SourceMovement> =
        postgrest.from(TABLE_SOURCE_MOVEMENTS)
            .select {
                filter { SourceMovement::sourceId eq sourceId }
                order("created_at", Order.DESCENDING)
            }
            .decodeList()

    private suspend fun getMovement(movementId: String): SourceMovement =
        postgrest.from(TABLE_SOURCE_MOVEMENTS)
            .select {
                filter { SourceMovement::id eq movementId }
            }
            .decodeSingle()

    private fun requireManual(movement: SourceMovement) {
        if (movement.referenceLoanId != null || movement.referencePaymentId != null) {
            throw NonManualSourceMovementException()
        }
    }

    private fun reverseEffect(currentBalance: Double, movement: SourceMovement): Double =
        when (movement.movementType) {
            MovementType.INCOME.dbValue -> currentBalance - movement.amount
            else -> currentBalance + movement.amount
        }

    private fun applyEffect(currentBalance: Double, movementType: MovementType, amount: Double): Double =
        when (movementType) {
            MovementType.INCOME -> currentBalance + amount
            MovementType.OUTFLOW -> currentBalance - amount
        }

    /**
     * Edits a manual movement in place: reverts its old effect on current_balance and applies
     * the new one. Only movements with no reference_loan_id/reference_payment_id (i.e. not
     * generated by a loan or a payment) can be edited — see [NonManualSourceMovementException].
     */
    suspend fun updateMovement(movementId: String, movementType: MovementType, amount: Double, notes: String?) {
        val current = getMovement(movementId)
        requireManual(current)

        val source = getFundingSource(current.sourceId)
        val balanceAfterRevert = reverseEffect(source.currentBalance, current)
        val newBalance = applyEffect(balanceAfterRevert, movementType, amount)

        postgrest.from(TABLE_SOURCE_MOVEMENTS).update({
            SourceMovement::movementType setTo movementType.dbValue
            SourceMovement::amount setTo amount
            SourceMovement::notes setTo notes
        }) {
            filter { SourceMovement::id eq movementId }
        }

        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::currentBalance setTo newBalance
        }) {
            filter { FundingSource::id eq current.sourceId }
        }
    }

    /**
     * Deletes a manual movement and reverts its effect on current_balance. Only movements with
     * no reference_loan_id/reference_payment_id can be deleted — see
     * [NonManualSourceMovementException].
     */
    suspend fun deleteMovement(movementId: String) {
        val current = getMovement(movementId)
        requireManual(current)

        val source = getFundingSource(current.sourceId)
        val newBalance = reverseEffect(source.currentBalance, current)

        postgrest.from(TABLE_SOURCE_MOVEMENTS).delete {
            filter { SourceMovement::id eq movementId }
        }

        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::currentBalance setTo newBalance
        }) {
            filter { FundingSource::id eq current.sourceId }
        }
    }

    suspend fun addManualMovement(
        sourceId: String,
        movementType: MovementType,
        amount: Double,
        notes: String? = null
    ) = recordSourceMovement(sourceId = sourceId, movementType = movementType, amount = amount, notes = notes)

    /**
     * Inserts a [source_movements] row and updates the source's current_balance accordingly.
     * Shared by every feature that moves money in or out of a funding source (manual
     * adjustments, loans, payments) so the balance update logic lives in one place.
     */
    internal suspend fun recordSourceMovement(
        sourceId: String,
        movementType: MovementType,
        amount: Double,
        notes: String? = null,
        referenceLoanId: String? = null,
        referencePaymentId: String? = null
    ) {
        postgrest.from(TABLE_SOURCE_MOVEMENTS).insert(
            NewSourceMovement(
                sourceId = sourceId,
                movementType = movementType.dbValue,
                amount = amount,
                notes = notes,
                referenceLoanId = referenceLoanId,
                referencePaymentId = referencePaymentId
            )
        )

        val current = getFundingSource(sourceId)
        val updatedBalance = when (movementType) {
            MovementType.INCOME -> current.currentBalance + amount
            MovementType.OUTFLOW -> current.currentBalance - amount
        }

        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::currentBalance setTo updatedBalance
        }) {
            filter { FundingSource::id eq sourceId }
        }
    }
}

@Serializable
private data class NewFundingSource(
    val name: String
)

@Serializable
private data class NewSourceMovement(
    @SerialName("source_id") val sourceId: String,
    @SerialName("movement_type") val movementType: String,
    val amount: Double,
    val notes: String? = null,
    @SerialName("reference_loan_id") val referenceLoanId: String? = null,
    @SerialName("reference_payment_id") val referencePaymentId: String? = null
)
