package com.didiprogrammer.youtepresta.data.repository

import com.didiprogrammer.youtepresta.data.model.FundingSource
import com.didiprogrammer.youtepresta.data.model.SourceMovement
import com.didiprogrammer.youtepresta.data.remote.SupabaseClientProvider
import io.github.jan.supabase.postgrest.postgrest
import io.github.jan.supabase.postgrest.query.Order
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

enum class MovementType(val dbValue: String) {
    INCOME("income"),
    OUTFLOW("outflow")
}

/**
 * Thrown by [FundingSourceRepository.updateMovement] and [FundingSourceRepository.deleteMovement]
 * when the target movement has a `reference_loan_id` or `reference_payment_id` — i.e. it was
 * generated by a loan or a payment, not entered manually, and must stay read-only from the
 * funding source screen.
 */
class NonManualSourceMovementException : Exception(
    "This source movement was generated by a loan or a payment and cannot be edited or deleted here."
)

object FundingSourceRepository {

    private const val TABLE_FUNDING_SOURCES = "funding_sources"
    private const val TABLE_SOURCE_MOVEMENTS = "source_movements"
    private const val INITIAL_BALANCE_NOTE = "Saldo inicial"

    private val postgrest = SupabaseClientProvider.client.postgrest

    suspend fun getFundingSources(): List<FundingSource> =
        postgrest.from(TABLE_FUNDING_SOURCES)
            .select {
                order("name", Order.ASCENDING)
            }
            .decodeList()

    suspend fun getFundingSource(sourceId: String): FundingSource =
        postgrest.from(TABLE_FUNDING_SOURCES)
            .select {
                filter { FundingSource::id eq sourceId }
            }
            .decodeSingle()

    suspend fun createFundingSource(name: String, initialBalance: Double) {
        val created = postgrest.from(TABLE_FUNDING_SOURCES)
            .insert(NewFundingSource(name = name)) {
                select()
            }
            .decodeSingle<FundingSource>()

        if (initialBalance > 0) {
            addManualMovement(
                sourceId = created.id,
                movementType = MovementType.INCOME,
                amount = initialBalance,
                notes = INITIAL_BALANCE_NOTE
            )
        }
    }

    suspend fun getSourceMovements(sourceId: String): List<SourceMovement> =
        postgrest.from(TABLE_SOURCE_MOVEMENTS)
            .select {
                filter { SourceMovement::sourceId eq sourceId }
                order("created_at", Order.DESCENDING)
            }
            .decodeList()

    private suspend fun getMovement(movementId: String): SourceMovement =
        postgrest.from(TABLE_SOURCE_MOVEMENTS)
            .select {
                filter { SourceMovement::id eq movementId }
            }
            .decodeSingle()

    private fun requireManual(movement: SourceMovement) {
        if (movement.referenceLoanId != null || movement.referencePaymentId != null) {
            throw NonManualSourceMovementException()
        }
    }

    private fun reverseEffect(currentBalance: Double, movement: SourceMovement): Double =
        when (movement.movementType) {
            MovementType.INCOME.dbValue -> currentBalance - movement.amount
            else -> currentBalance + movement.amount
        }

    private fun applyEffect(currentBalance: Double, movementType: MovementType, amount: Double): Double =
        when (movementType) {
            MovementType.INCOME -> currentBalance + amount
            MovementType.OUTFLOW -> currentBalance - amount
        }

    /**
     * Edits a manual movement in place: reverts its old effect on current_balance and applies
     * the new one. Only movements with no reference_loan_id/reference_payment_id (i.e. not
     * generated by a loan or a payment) can be edited — see [NonManualSourceMovementException].
     */
    suspend fun updateMovement(movementId: String, movementType: MovementType, amount: Double, notes: String?) {
        val current = getMovement(movementId)
        requireManual(current)

        val source = getFundingSource(current.sourceId)
        val balanceAfterRevert = reverseEffect(source.currentBalance, current)
        val newBalance = applyEffect(balanceAfterRevert, movementType, amount)

        postgrest.from(TABLE_SOURCE_MOVEMENTS).update({
            SourceMovement::movementType setTo movementType.dbValue
            SourceMovement::amount setTo amount
            SourceMovement::notes setTo notes
        }) {
            filter { SourceMovement::id eq movementId }
        }

        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::currentBalance setTo newBalance
        }) {
            filter { FundingSource::id eq current.sourceId }
        }
    }

    /**
     * Deletes a manual movement and reverts its effect on current_balance. Only movements with
     * no reference_loan_id/reference_payment_id can be deleted — see
     * [NonManualSourceMovementException].
     */
    suspend fun deleteMovement(movementId: String) {
        val current = getMovement(movementId)
        requireManual(current)

        val source = getFundingSource(current.sourceId)
        val newBalance = reverseEffect(source.currentBalance, current)

        postgrest.from(TABLE_SOURCE_MOVEMENTS).delete {
            filter { SourceMovement::id eq movementId }
        }

        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::currentBalance setTo newBalance
        }) {
            filter { FundingSource::id eq current.sourceId }
        }
    }

    suspend fun addManualMovement(
        sourceId: String,
        movementType: MovementType,
        amount: Double,
        notes: String? = null
    ) = recordSourceMovement(sourceId = sourceId, movementType = movementType, amount = amount, notes = notes)

    /**
     * Inserts a [source_movements] row and updates the source's current_balance accordingly.
     * Shared by every feature that moves money in or out of a funding source (manual
     * adjustments, loans, payments) so the balance update logic lives in one place.
     */
    internal suspend fun recordSourceMovement(
        sourceId: String,
        movementType: MovementType,
        amount: Double,
        notes: String? = null,
        referenceLoanId: String? = null,
        referencePaymentId: String? = null
    ) {
        postgrest.from(TABLE_SOURCE_MOVEMENTS).insert(
            NewSourceMovement(
                sourceId = sourceId,
                movementType = movementType.dbValue,
                amount = amount,
                notes = notes,
                referenceLoanId = referenceLoanId,
                referencePaymentId = referencePaymentId
            )
        )

        val current = getFundingSource(sourceId)
        val updatedBalance = when (movementType) {
            MovementType.INCOME -> current.currentBalance + amount
            MovementType.OUTFLOW -> current.currentBalance - amount
        }

        postgrest.from(TABLE_FUNDING_SOURCES).update({
            FundingSource::currentBalance setTo updatedBalance
        }) {
            filter { FundingSource::id eq sourceId }
        }
    }
}

@Serializable
private data class NewFundingSource(
    val name: String
)

@Serializable
private data class NewSourceMovement(
    @SerialName("source_id") val sourceId: String,
    @SerialName("movement_type") val movementType: String,
    val amount: Double,
    val notes: String? = null,
    @SerialName("reference_loan_id") val referenceLoanId: String? = null,
    @SerialName("reference_payment_id") val referencePaymentId: String? = null
)
